from controllers.homecontroller import *
from controllers.subjectscontroller import *
from controllers.userscontroller import *
from controllers.logincontroller import *
from controllers.qualcontroller import *
from controllers.instcontroller import *
from controllers.statescontroller import *
from controllers.districtscontroller import *
from controllers.townscontroller import *
from controllers.jobscontroller import *